- name: set mysql root password via debconf
  shell: debconf-set-selections << 'mysql-server-5.5 mysql-server/root_password password root' && debconf-set-selections << 'mysql-server-5.5 mysql-server/root_password_again password root'

- name: install mysql 5.5
  apt: pkg=mysql-server-5.5 state=present

- name: install python-mysqldb (for ansible)
  apt: pkg=python-mysqldb state=present

- name: create my.cnf config for root
  template: src=my.cnf.j2 dest=/root/.my.cnf

#- name: create database user
#  mysql_user: name={{ database_user }} password={{ database_password }} priv=`{{ database_name}}.*`:ALL state=present

#- name: create database
#  mysql_db: name={{ database_name }} state=present
