- name: Preseed slapd configuration options through debconf
  debconf: name=slapd question={{ item.question }} value={{ item.value }} vtype={{ item.type }}
  with_items:
    - { question: slapd/internal/adminpw, value: "{{ ldap_admin_password }}", type: password }
    - { question: slapd/password1, value: "{{ ldap_admin_password }}", type: password }
    - { question: slapd/password2, value: "{{ ldap_admin_password }}", type: password }
    - { question: shared/organization, value: "{{ ldap_organization }}", type: string }
    - { question: slapd/domain, value: "{{ ldap_organization_domain }}", type: string }
    - { question: slapd/backend, value: HDB, type: string }
  sudo: yes

- name: Install slapd and ldap-utils
  apt: pkg={{ item }} state=installed
  with_items:
    - slapd
    - ldap-utils
  sudo: yes
