- name: install libapache2-mod-php5
  apt: pkg=libapache2-mod-php5 state=latest
  become: yes

- apache2_module: state=present name=php5
  notify: restart apache
  become: yes

- name: Configure mod-php
  command: php5enmod {{ item }}
  with_items:
    - php-dev
    - xdebug
  notify: restart apache
  become: yes

- meta: flush_handlers
