- name: install apache
  apt: pkg=apache2 state=latest
  sudo: yes

- name: remove default vhost
  file: name=/etc/apache2/sites-{{ item }}/000-default.conf state=absent
  sudo: yes
  with_items:
      - enabled
      - available
  notify: restart apache

- name: create vhost config
  template: src={{ site_template }} dest=/etc/apache2/sites-available/{{ hostname }}.conf
  sudo: yes

- name: enable vhost
  file: src=/etc/apache2/sites-available/{{ hostname }}.conf dest=/etc/apache2/sites-enabled/0001-{{ hostname }}.conf state=link
  sudo: yes
  notify: reload apache

- name: enable apache modules
  apache2_module: state=present name={{ item }}
  sudo: yes
  with_items:
      - rewrite
      - vhost_alias
      - mime
      - deflate
      - headers
  notify: restart apache

- name: enable Apache SSL module
  apache2_module: state=present name=ssl
  sudo: yes
  when: ssl
  notify: restart apache
