- name: install apache
  apt: pkg=apache2 state=present

- name: remove default vhost
  file: name=/etc/apache2/sites-{{ item }}/000-default.conf state=absent
  with_items:
      - enabled
      - available
  notify: restart apache

- name: create vhost config
  template: src={{ site_template }} dest=/etc/apache2/sites-available/{{ hostname }}

- name: enable vhost
  file: src=/etc/apache2/sites-available/{{ hostname }} dest=/etc/apache2/sites-enabled/{{ hostname }} state=link
  notify: reload apache
