---
# build the docker image if needed, then run it
- name: ensure that docker daemone is started
  service: name=docker state=started

- name: build the docker image
  docker_image: path='./../../' name={{ docker.image_repository }} tag={{ docker.image_name }} state=present
#  this is not working it seems, destroy the image before trying

- name: Get local dir
  local_action: shell cd ../../../; pwd
  register: pwd

- name: "{{ playbook }} the image"
  docker: image="{{ docker.image_repository }}:{{ docker.image_name }}" tty=True command=/sbin/init volumes="{{ pwd.stdout }}:/exports:rw" state={{ docker_state }}

- include: set_linux_hosts.yml
  when: playbook == "start"
