
- name: retrieve container ip
  shell: docker inspect --format '{{ .NetworkSettings.IPAddress }}' $(docker ps -l -q)
  register: docker_ip

- name: set /etc/hosts
  lineinfile: dest=/etc/hosts regexp=".*{{ item }}$" line="{{ docker_ip.stdout }} {{ item }}" state=present backup=yes
  with_items: hostnames + [hostname]
