- name: create directory for composer
  sudo: yes
  file: name={{ composer.dir }} state=directory

- name: install composer
  sudo: yes
  shell: "cd {{ composer.dir }} && curl -sS https://getcomposer.org/installer | php"

- name: symling composer in /usr/local/bin
  file: src="{{ composer.dir }}/composer.phar" dest=/usr/local/bin/{{ item }} state=link
  sudo: yes
  with_items:
    - composer
    - composer.phar
