- set_fact: database_type=postgis

- name: ensure geo packages are installed
  apt: pkg={{ item }} state=present
  with_items:
      - binutils
      - libproj-dev
      - gdal-bin
      - postgresql-9.1-postgis
  sudo: yes

- name: run postgis scripts on existing database
  action: command psql -d {{ database_name }} --file /usr/share/postgresql/9.1/contrib/postgis-1.5/{{ item }}
  sudo_user: postgres
  sudo: yes
  with_items:
    - postgis.sql
    - spatial_ref_sys.sql
