- name: Install Elasticsearch APT key
  apt_key: url=https://packages.elastic.co/GPG-KEY-elasticsearch
  sudo: yes

- name: Install Elasticsearch APT repository
  apt_repository: repo='deb http://packages.elastic.co/elasticsearch/2.x/debian stable main' state=present update_cache=yes
  sudo: yes

- name: Install elasticsearch
  apt: pkg=elasticsearch state=present
  sudo: yes

- name: Copy elasticsearch configuration
  copy: src=elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml
  sudo: yes

- name: Enable elasticsearch service
  service: name=elasticsearch state=started enabled=yes
  sudo: yes

- name: Install elasticsearch-head plugin
  command: /usr/share/elasticsearch/bin/plugin install mobz/elasticsearch-head creates=/usr/share/elasticsearch/plugins/head
  sudo: yes


