- name: Install Elasticsearch APT key
  apt_key: url=https://packages.elastic.co/GPG-KEY-elasticsearch
  sudo: yes

- name: Install Elasticsearch APT repository
  apt_repository: repo='deb http://packages.elastic.co/elasticsearch/2.x/debian stable main' state=present update_cache=yes
  sudo: yes

- name: install elasticsearch
  apt: pkg=elasticsearch state=present
  sudo: yes

- name: Enable elasticsearch service
  service: name=elasticsearch state=started enabled=yes
  sudo: yes
