---
- name: install python 2 packages
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - python-virtualenv
    - python-pip
    - python-all-dev
  when: python_version == "2"

- name: install python 3 packages
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - python-virtualenv
    - python3-pip
    - python3-all-dev
  when: python_version == "3"

- name: make symlink from pip-3.2 to pip
  file: src=/usr/bin/pip-3.2 dest=/usr/bin/pip state=link
  sudo: yes
  when: python_version == "3"

- name: install python 3 virtualenv
  pip: name=virtualenv
  sudo: yes
  when: python_version == "3"

- name: install pillow dependencies
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - libfreetype6-dev
    - zlib1g-dev
    - libwebp-dev
    - liblcms2-dev
    - libtiff5-dev

- name: install libjpeg-dev
  apt: pkg=libjpeg-dev state=latest
  sudo: yes
  when: ansible_lsb.major_release|int >= 8

- name: install libjpeg8-dev
  apt: pkg=libjpeg8-dev state=latest
  sudo: yes
  when: ansible_lsb.major_release|int == 7
