---
- name: install python 2 packages
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - python-virtualenv
    - python-pip
    - python-all-dev
  when: python_version == "2"

- name: install python 3 packages
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - python3-pip
    - python3-all-dev
  when: python_version == "3"

- name: make symlink from pip-3.2 / pip3 to pip
  file: src="/usr/bin/{{ (ansible_lsb.major_release|int == 7) | ternary('pip-3.2', 'pip3') }}" dest=/usr/bin/pip state=link
  sudo: yes
  when: python_version == "3"

- name: install python 3 virtualenv (wheezy)
  pip: name=virtualenv
  sudo: yes
  when: python_version == "3" and ansible_lsb.major_release|int == 7

- name: install python 3 virtualenv (jessie)
  apt: pkg=python3-virtualenv state=latest
  sudo: yes
  when: python_version == "3" and ansible_lsb.major_release|int == 8

- name: install pillow dependencies
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - libfreetype6-dev
    - zlib1g-dev
    - libwebp-dev
    - liblcms2-dev
    - libtiff5-dev

- name: install libjpeg-dev
  apt: pkg="{{ (ansible_lsb.major_release|int == 7) | ternary('libjpeg8-dev', 'libjpeg-dev') }}" state=latest
  sudo: yes
  when: ansible_lsb.major_release|int >= 8
