---
# We always install Python 2 + Python 3 packages in case we want to use tools
# like tox
- name: install python 2 packages
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - virtualenv
    - python-pip
    - python-all-dev

- name: install python 3 packages
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - python3-pip
    - python3-all-dev

- name: install python 3 virtualenv (jessie)
  apt: pkg=python3-venv state=latest
  sudo: yes
  when: ansible_lsb.major_release|int == 8

- name: install pillow dependencies
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - libfreetype6-dev
    - zlib1g-dev
    - libwebp-dev
    - liblcms2-dev
    - libtiff5-dev

- name: install libjpeg-dev
  apt: pkg="{{ (ansible_lsb.major_release|int == 7) | ternary('libjpeg8-dev', 'libjpeg-dev') }}" state=latest
  sudo: yes
  when: ansible_lsb.major_release|int >= 8
