- name: ensure python-apt is installed
  command: apt-get install -y python-apt creates=/usr/share/pyshared/apt
  sudo: yes

- name: ensure apt database is up-to-date
  apt: update_cache=yes
  sudo: yes

- name: set en_US.UTF-8 as generated locale
  debconf: name=locales question='locales/locales_to_be_generated'  value='en_US.UTF-8 UTF-8' vtype='multiselect'
  sudo: yes

- name: set en_US.UTF-8 as default locale
  debconf: name=locales question='locales/default_environment_locale' value=en_US.UTF-8 vtype='select'
  sudo: yes

- name: ensure base packages are installed
  apt: pkg={{ item }} state=present
  sudo: yes
  with_items:
    - locales
    - procps
    - command-not-found
    - bash-completion
    - zsh
    - bzip2
    - git
    - vim
    - ack-grep
    - build-essential
    - wget
    - openssh-server
    - sudo
    - imagemagick
    - iputils-ping
    - ncurses-term

- name: install shell config
  copy: src={{ item }} dest=~/.{{ item }}
  with_items:
    - aliases
    - bashrc
    - zshrc
    - liquidpromptrc
    - gitconfig
    - gitglobalignore
    - ackrc
    - vimrc

- name: install liquidprompt
  git: repo=https://github.com/nojhan/liquidprompt.git dest=~/liquidprompt accept_hostkey=yes

- name: use liquidprompt as prompt
  file: src=~/liquidprompt/liquidprompt dest=~/.ps1 state=link

- name: cd to /vagrant when sshing
  lineinfile: dest=~/.bashrc line='cd /vagrant'

- name: add vagrant user to www-data group
  shell: "usermod -a -G www-data vagrant"
  sudo: yes

# Some programs such as PostgreSQL use the current locale to create the base
# databases. If the locale is set to a value that isn't installed on the
# system, PostgreSQL installation will fail
- name: disallow setting of LANG and LOCALE
  lineinfile: dest=/etc/ssh/sshd_config line='AcceptEnv LANG LC_*' state=absent
  notify: restart ssh
  sudo: yes

# This is required because the SSH daemon needs to use the new configuration
# before trying to execute other provisioning scripts that might fail because
# of the locale environment variables
- meta: flush_handlers
