- name: ensure python-apt is installed
  command: apt-get install -y python-apt creates=/usr/share/pyshared/apt
  become: yes

- name: remove systemd on Debian
  apt: name=systemd state=absent
  become: yes
  when: "ansible_distribution == 'Debian'"

- name: ensure apt database is up-to-date
  apt: update_cache=yes
  become: yes

- name: set en_US.UTF-8 as generated locale
  debconf: name=locales question='locales/locales_to_be_generated'  value='en_US.UTF-8 UTF-8' vtype='multiselect'
  become: yes

- name: set en_US.UTF-8 as default locale
  debconf: name=locales question='locales/default_environment_locale' value=en_US.UTF-8 vtype='select'
  become: yes

- name: ensure members of sudo can sudo password-less
  copy: src=passwordless-sudo dest=/etc/sudoers.d/sudo-passwordless
  become: yes

- name: ensure base packages are installed
  apt: pkg={{ item }} state=latest
  become: yes
  with_items:
    - locales
    - procps
    - command-not-found
    - bash-completion
    - zsh
    - bzip2
    - unzip
    - vim
    - ack-grep
    - highlight
    - libxml2-utils
    - build-essential
    - wget
    - openssh-server
    - sudo
    - imagemagick
    - iputils-ping
    - ncurses-term
    - python-pycurl # needed by ansible to add apt repos

# Some programs such as PostgreSQL use the current locale to create the base
# databases. If the locale is set to a value that isn't installed on the
# system, PostgreSQL installation will fail
- name: disallow setting of LANG and LOCALE
  lineinfile: dest=/etc/ssh/sshd_config line='AcceptEnv LANG LC_*' state=absent
  notify: restart ssh
  become: yes

- name: disallow DNS lookups in sshd
  lineinfile: dest=/etc/ssh/sshd_config line='UseDNS no' state=present
  notify: restart ssh
  become: yes

- name: disallow GSSAPIAuthentication lookups in sshd
  lineinfile: dest=/etc/ssh/sshd_config line='GSSAPIAuthentication no' state=present
  notify: restart ssh
  become: yes

# This is required because the SSH daemon needs to use the new configuration
# before trying to execute other provisioning scripts that might fail because
# of the locale environment variables
- meta: flush_handlers
- name: ensure silversearcher-ag is installed
  apt: pkg=silversearcher-ag
  when: ansible_lsb.major_release|int >= 8
  become: yes

- name: install shell config
  copy: src={{ item }} dest=~/.{{ item }}
  with_items:
    - aliases
    - bashrc
    - zshrc
    - liquidpromptrc
    - ackrc
    - vimrc

- name: cd to /vagrant when sshing
  lineinfile: dest=~/.bashrc line='cd /vagrant'

- name: add vagrant user to www-data group
  shell: "usermod -a -G www-data vagrant"
  become: yes

- name: "Add custom hosts to /etc/hosts file"
  lineinfile: dest=/etc/hosts regexp='.* {{ item.host }}$' line="{{ item.ip }} {{ item.host }}" state=present
  with_items: hosts
  become: yes
