- name: ensure python-apt is installed
  command: apt-get install -y python-apt creates=/usr/share/pyshared/apt

- name: ensure apt database is up-to-date
  apt: update_cache=yes

- name: ensure base packages are installed
  apt: pkg={{ item }} state=present
  with_items:
    - procps
    - command-not-found
    - bash-completion
    - bzip2
    - git
    - vim
    - ack-grep
    - build-essential

- name: install shell config
  copy: src={{ item }} dest=/root/.{{ item }}
  with_items:
    - aliases
    - bashrc
    - ps1
    - gitconfig
    - gitglobalignore
    - ackrc
    - vimrc

