- name: ensure python-apt is installed
  command: apt-get install -y python-apt creates=/usr/share/pyshared/apt

- name: ensure apt database is up-to-date
  apt: update_cache=yes

- name: ensure base packages are installed
  apt: pkg={{ item }} state=present
  with_items:
    - procps
    - command-not-found
    - bash-completion
    - zsh
    - bzip2
    - git
    - vim
    - ack-grep
    - build-essential

- name: install shell config
  copy: src={{ item }} dest=/root/.{{ item }}
  with_items:
    - aliases
    - bashrc
    - zshrc
    - liquidpromptrc
    - gitconfig
    - gitglobalignore
    - ackrc
    - vimrc

- name: install liquidprompt
  git: repo=https://github.com/nojhan/liquidprompt.git dest=/root/liquidprompt accept_hostkey=yes

- name: use liquidprompt as promt
  file: src=/root/liquidprompt/liquidprompt dest=/root/.ps1 state=link

