- name: ensure python-apt is installed
  command: apt-get install -y python-apt creates=/usr/share/pyshared/apt
  sudo: yes

- name: ensure apt database is up-to-date
  apt: update_cache=yes
  sudo: yes

- name: set en_US.UTF-8 as generated locale
  debconf: name=locales question='locales/locales_to_be_generated'  value='en_US.UTF-8 UTF-8' vtype='multiselect'
  sudo: yes

- name: set en_US.UTF-8 as default locale
  debconf: name=locales question='locales/default_environment_locale' value=en_US.UTF-8 vtype='select'
  sudo: yes

- name: ensure base packages are installed
  apt: pkg={{ item }} state=present
  sudo: yes
  with_items:
    - locales
    - procps
    - command-not-found
    - bash-completion
    - zsh
    - bzip2
    - git
    - vim
    - ack-grep
    - build-essential
    - wget
    - openssh-server
    - sudo
    - imagemagick
    - iputils-ping

- name: install shell config
  copy: src={{ item }} dest=~/.{{ item }}
  with_items:
    - aliases
    - bashrc
    - zshrc
    - liquidpromptrc
    - gitconfig
    - gitglobalignore
    - ackrc
    - vimrc

- name: install liquidprompt
  git: repo=https://github.com/nojhan/liquidprompt.git dest=~/liquidprompt accept_hostkey=yes

- name: use liquidprompt as prompt
  file: src=~/liquidprompt/liquidprompt dest=~/.ps1 state=link
