- name: install supervisor
  apt: pkg=nginx state=present
  notify: enable supervisor

- name: create service config
  template: src=service.conf dest=/etc/supervisor/conf.d/{{ service_name }}.conf
  notify: restart supervisor
