---
dependencies:
  - { role: supervisor, service_name: "solr", user: "solr", command: "java -jar -Dsolr.solr.home={{ solr.install_dir }} start.jar", root_directory: "{{ solr.config_dir }}" }
  - { role: java }
