---
# This role requires either the postgresql or mysql roles to be enabled

# Gettext is used by Django's compilemessages
- name: ensure gettext is installed
  apt: pkg=gettext state=latest
  sudo: yes

- name: create the local environement directory
  file: path=/vagrant/envdir/local state=directory

- name: fill in DATABASE_URL setting
  copy: dest=/vagrant/envdir/local/DATABASE_URL content="{{ database_type | mandatory }}://{{ database_user }}:{{ database_user }}@localhost/{{ database_name }}"

- name: create venv and install base packages
  pip: "requirements={{ django_root }}/requirements/{{ django_pip_requirements }}.txt virtualenv={{ env_root }}"

- name: activate virtualenv when sshing into the box
  lineinfile: dest=~/.bashrc line='. {{ env_root }}/bin/activate'

- name: sync db
  command: "{{ env_root }}/bin/python {{ django_root }}/manage.py syncdb --noinput"
  when: django_version != "1.7"

- name: migrate
  command: "{{ env_root }}/bin/python {{ django_root }}/manage.py migrate --noinput"
