- name: clone diff-so-fancy
  git: repo=https://github.com/so-fancy/diff-so-fancy.git dest=/tmp/fancy-diff version=v0.11.1

- name: copy files to /usr/local/bin
  command: cp -rf /tmp/fancy-diff/{{ item }} /usr/local/bin/
  with_items:
    - third_party/diff-highlight/diff-highlight
    - libexec
    - diff-so-fancy
  become: yes

- name: make sure files are executable
  command: chmod a+x /usr/local/bin/{{ item }}
  with_items:
    - diff-highlight
    - diff-so-fancy
  become: yes

- name: activate fancy-diff
  command: git config --system pager.{{ item }} "diff-so-fancy | less --tabs=4 -RFX"
  with_items:
    - diff
    - show
  become: yes
