- name: install git and utilities
  apt: pkg={{ item }} state=latest
  become: yes
  with_items:
    - git
    - libimage-exiftool-perl

- name: install default git config
  copy: src={{ item }} dest=~/.{{ item }}
  with_items:
    - gitconfig
    - gitglobalignore
    - gitglobalattributes

- name: get git username from synced config
  shell: git config --file ~/.gitconfig-host user.name
  register: git_username
  ignore_errors: yes

- name: get git email from synced config
  shell: git config --file ~/.gitconfig-host user.email
  register: git_email
  ignore_errors: yes

- name: set box git username and email
  shell: git config --global user.name "{{ git_username.stdout }}"; git config --global user.email "{{ git_email.stdout }}"

- include: fancy-diff.yml
  when: fancy_diff
