---
- name: create venv and install base packages
  pip: "requirements={{ root_directory }}/{{ pip_requirements }} virtualenv={{ env_root }} virtualenv_command={{ 'virtualenv' if (python_version|int == 2) else 'pyvenv' }}"

- name: make sure pip and setuptools are up-to-date
  pip: "name={{ item }} virtualenv={{ env_root }}"
  with_items:
    - pip=={{ pip_version }}
    - setuptools=={{ setuptools_version }}

- name: activate virtualenv when sshing into the box
  lineinfile: dest=~/.bashrc line='. {{ env_root }}/bin/activate'
